version: "3"

services:
  pipkoff-notebook:
    container_name: pipkoff-notebook
    build:
      context: ${PROJECT_DIR}/docker/jupyter
      dockerfile: ${PROJECT_DIR}/docker/jupyter/Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    restart: always
    command: jupyter-notebook
    env_file:
      - ${PROJECT_DIR}/.env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ${PROJECT_DIR}:/app
    networks:
      - shared
    ports:
      - 8888:8888
      - 8080:8080


  pipkoff-api:
    container_name: pipkoff-api
    build:
      context: ${PROJECT_DIR}/docker/python
      dockerfile: ${PROJECT_DIR}/docker/python/Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    restart: always
    command: flask run
    env_file:
      - ${PROJECT_DIR}/.env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ${PROJECT_DIR}:/app
    networks:
      - shared
    ports:
      - 15000:5000


  pipkoff-postgres:
    container_name: pipkoff-postgres
    image: postgres:12-buster
    restart: "no"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--data-checksums"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ${PROJECT_DIR}/db-data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    networks:
      - shared

networks:
  shared:
    driver: bridge
